# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cage < Formula
  desc "CLI tool for safely working with untrusted projects on macOS by isolating them in virtual machines"
  homepage "https://github.com/stackfusion/cage"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stackfusion/cage/releases/download/v0.1.2/cage_Darwin_x86_64.tar.gz"
      sha256 "14210a18a5f94c56ef78ec3c7c740f78e2df5d617e66045d0af5e5362f00ab88"

      define_method(:install) do
        bin.install "cage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stackfusion/cage/releases/download/v0.1.2/cage_Darwin_arm64.tar.gz"
      sha256 "cdf34ff7bf4cd29ce2955c31b1828cd4b9ec16e562b33ce8ca7e72cc246ad118"

      define_method(:install) do
        bin.install "cage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stackfusion/cage/releases/download/v0.1.2/cage_Linux_x86_64.tar.gz"
      sha256 "72647f13056c59b42c5c34a18272d175d657af1bbd844d7fdf04685f51e92053"
      define_method(:install) do
        bin.install "cage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stackfusion/cage/releases/download/v0.1.2/cage_Linux_arm64.tar.gz"
      sha256 "61228070e2c5b597916ccce85063363ec260fd268dedbe178ca6f710f01270ba"
      define_method(:install) do
        bin.install "cage"
      end
    end
  end

  test do
    system "#{bin}/cage --version"
  end
end
