# This file was generated by GoReleaser. DO NOT EDIT.
cask "cage" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "8faebb69bb37481762f93e054fb05b8a62c1fecc5b0ecd928ea22cac810e844d"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fabb4c50a36b048ad1f6f5adc0d5d4502f4b67ae11bb296e2dded24623ecfcdf"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9c0c74d9d84a51edb77aac5681aaa401167db14ed6b2e7c7fa5e3cccac81668e"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "08c60e9c0e24558a302c770f2df27a334e93a0eb5d70b31c7d1c740d297cefc7"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Linux_arm64.tar.gz"
    end
  end

  name "cage"
  desc "CLI tool for safely working with untrusted projects on macOS by isolating them in virtual machines"
  homepage "https://github.com/stackfusion/cage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cage"]
    end
  end

  # No zap stanza required

end
