# This file was generated by GoReleaser. DO NOT EDIT.
cask "cage" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "f0f9088f8c6db0bb2f250f24280c2b356e031ae2f0a252b151d1b7e6bf1d21b5"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "81830e0550af111f553d5e4b3214d22cdd1d87b872358666a64e985fc5ebda0d"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c61cf2c39d5d8af6c3aa33ad9c1b841ab011a4f75e222beb25a80830ff424990"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "acc4effb1b795b16e826aced8db074317d770804771e45308ba8e1e1c48169f7"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Linux_x86_64.tar.gz"
    end
  end

  name "cage"
  desc "CLI tool for safely working with untrusted projects on macOS by isolating them in virtual machines"
  homepage "https://github.com/stackfusion/cage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cage"

  postflight_steps do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cage"]
    end
  end

  # No zap stanza required
end
