# This file was generated by GoReleaser. DO NOT EDIT.
cask "cage" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "52b66c3a190015c449f3a098a9956b857e491fa22693afe2509385036754851a"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "acd0e52fd87f9ce345435f671b4489edc47fa6379ac69a3fc9118d8cd65c7c1e"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0268df62c844392e5c7dafec4e77113b4159e16c3fdc86e9da68fe9f9d563ed"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "160004daf29fc46751932cde6348861e701a7f10ad7f4008ba51c350bbcbadc3"
      url "https://github.com/stackfusion/cage/releases/download/v#{version}/cage_Linux_arm64.tar.gz"
    end
  end

  name "cage"
  desc "CLI tool for safely working with untrusted projects on macOS by isolating them in virtual machines"
  homepage "https://github.com/stackfusion/cage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cage"]
    end
  end

  # No zap stanza required

end
